async (page) => {
  const base = 'http://127.0.0.1:4173/';
  const checks = [];
  const check = (ok, label) => { if (!ok) throw new Error(label); checks.push(label); };
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.goto(base + 'about/');
  await page.evaluate(() => localStorage.clear());
  await page.goto(base);
  await page.locator('#boot-dialog[open]').waitFor();
  check(await page.locator('[data-welcome] video').getAttribute('src') === null, 'Video waits for intro before downloading');
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => document.querySelector('[data-welcome] video').currentTime > 0.1);
  check(await page.locator('[data-welcome] video').evaluate(v => v.muted && !v.loop), 'Silent playback does not loop');
  await page.getByRole('button', { name: 'Pause animation', exact: true }).click();
  check(await page.locator('[data-welcome] video').evaluate(v => v.paused), 'Pause works');
  await page.getByRole('button', { name: 'Resume animation', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('[data-welcome] video').ended, { timeout: 10000 });
  check(await page.locator('[data-welcome]').evaluate(el => el.classList.contains('is-playing')), 'Ending frame remains visible');
  await page.getByRole('button', { name: 'Replay animation', exact: true }).click();
  await page.waitForFunction(() => { const v = document.querySelector('[data-welcome] video'); return !v.paused && v.currentTime < 2; });
  check(true, 'Replay restarts the same clip');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  check(await page.locator('[data-welcome]').evaluate(el => !el.classList.contains('is-playing') && el.querySelector('video').paused), 'Changing reduced motion restores the still');
  await page.reload();
  check(await page.locator('[data-welcome] video').getAttribute('src') === null, 'Reduced motion does not download video');
  await page.setViewportSize({ width: 390, height: 844 });
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile page has no horizontal overflow');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.route('**/patrick-welcome.mp4', route => route.abort());
  await page.evaluate(() => localStorage.setItem('fieldnotes:skip-intro', 'true'));
  await page.reload();
  await page.locator('[data-welcome]').scrollIntoViewIfNeeded();
  await page.waitForFunction(() => document.querySelector('[data-welcome] video').error !== null);
  check(await page.locator('[data-welcome]').evaluate(el => !el.classList.contains('is-playing') && el.querySelector('button').hidden), 'Failed download leaves still image and hides broken control');
  await page.unroute('**/patrick-welcome.mp4');
  const context = await page.context().browser().newContext({ javaScriptEnabled: false });
  const plain = await context.newPage();
  await plain.goto(base);
  check(await plain.locator('[data-welcome] .mascot img').isVisible() && await plain.locator('[data-welcome] button').isHidden(), 'No JavaScript shows still without unusable controls');
  await context.close();
  return { passed: checks.length, checks };
}
